#if !canImport(ObjectiveC)
import XCTest

extension CodableUpdatingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodableUpdatingTests = [
        ("test", test),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CodableUpdatingTests.__allTests__CodableUpdatingTests),
    ]
}
#endif
