#if !canImport(ObjectiveC)
import XCTest

extension DecodableRandomizedTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DecodableRandomizedTests = [
        ("testRandomized", testRandomized),
        ("testRandomizedWithCustomEncoding", testRandomizedWithCustomEncoding),
    ]
}

extension RandomizableFoundationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RandomizableFoundationTests = [
        ("testDataChanges", testDataChanges),
        ("testDateChanges", testDateChanges),
        ("testURLChanges", testURLChanges),
        ("testUUIDChanges", testUUIDChanges),
    ]
}

extension RandomizableInternalsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RandomizableInternalsTests = [
        ("testArrayCountCanBeOne", testArrayCountCanBeOne),
    ]
}

extension RandomizableSwiftTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RandomizableSwiftTests = [
        ("testArrayCanBeNonEmpty", testArrayCanBeNonEmpty),
        ("testArrayChanges", testArrayChanges),
        ("testArrayOfDecodablesCanBeEmpty", testArrayOfDecodablesCanBeEmpty),
        ("testArrayOfDecodablesCanBeNonEmpty", testArrayOfDecodablesCanBeNonEmpty),
        ("testArrayOfDecodablesChanges", testArrayOfDecodablesChanges),
        ("testBoolCanBeFalse", testBoolCanBeFalse),
        ("testBoolCanBeTrue", testBoolCanBeTrue),
        ("testDictionaryCanBeNonEmpty", testDictionaryCanBeNonEmpty),
        ("testDictionaryChanges", testDictionaryChanges),
        ("testDictionaryWithDecodablesCanBeEmpty", testDictionaryWithDecodablesCanBeEmpty),
        ("testDictionaryWithDecodablesCanBeNonEmpty", testDictionaryWithDecodablesCanBeNonEmpty),
        ("testDictionaryWithDecodablesChanges", testDictionaryWithDecodablesChanges),
        ("testDoubleCanBeNegative", testDoubleCanBeNegative),
        ("testDoubleCanBePositive", testDoubleCanBePositive),
        ("testDoubleChanges", testDoubleChanges),
        ("testFloatCanBeNegative", testFloatCanBeNegative),
        ("testFloatCanBePositive", testFloatCanBePositive),
        ("testFloatChanges", testFloatChanges),
        ("testIntCanBeNegative", testIntCanBeNegative),
        ("testIntCanBePositive", testIntCanBePositive),
        ("testIntChanges", testIntChanges),
        ("testOptionalCanBeNonNil", testOptionalCanBeNonNil),
        ("testOptionalChanges", testOptionalChanges),
        ("testStringCanBeNonEmpty", testStringCanBeNonEmpty),
        ("testStringChanges", testStringChanges),
        ("testUIntCanBeNonZero", testUIntCanBeNonZero),
        ("testUIntChanges", testUIntChanges),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DecodableRandomizedTests.__allTests__DecodableRandomizedTests),
        testCase(RandomizableFoundationTests.__allTests__RandomizableFoundationTests),
        testCase(RandomizableInternalsTests.__allTests__RandomizableInternalsTests),
        testCase(RandomizableSwiftTests.__allTests__RandomizableSwiftTests),
    ]
}
#endif
